// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpqPJtsrE2-u5URQ8nhracbmdtSvVwDOQ',
    appId: '1:856158677480:android:514d61bbc679926bc39c5d',
    messagingSenderId: '856158677480',
    projectId: 'chat-app-1da92',
    storageBucket: 'chat-app-1da92.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYh02R8G97mHUWU0bo08Hm1lkeTLE-ILg',
    appId: '1:856158677480:web:670688eb58135d9cc39c5d',
    messagingSenderId: '856158677480',
    projectId: 'chat-app-1da92',
    authDomain: 'chat-app-1da92.firebaseapp.com',
    storageBucket: 'chat-app-1da92.firebasestorage.app',
    measurementId: 'G-6RFWPVPVS7',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYh02R8G97mHUWU0bo08Hm1lkeTLE-ILg',
    appId: '1:856158677480:web:670688eb58135d9cc39c5d',
    messagingSenderId: '856158677480',
    projectId: 'chat-app-1da92',
    authDomain: 'chat-app-1da92.firebaseapp.com',
    storageBucket: 'chat-app-1da92.firebasestorage.app',
    measurementId: 'G-6RFWPVPVS7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBzsrodYRpLXxmdy-ZtwMFXNkM6QMuFEY',
    appId: '1:856158677480:ios:1daa42d97942b316c39c5d',
    messagingSenderId: '856158677480',
    projectId: 'chat-app-1da92',
    storageBucket: 'chat-app-1da92.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBzsrodYRpLXxmdy-ZtwMFXNkM6QMuFEY',
    appId: '1:856158677480:ios:1daa42d97942b316c39c5d',
    messagingSenderId: '856158677480',
    projectId: 'chat-app-1da92',
    storageBucket: 'chat-app-1da92.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

}